# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_demo_1.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(850, 707)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        self.lineEdit_3.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 3, 2, 1, 1)
        self.timer_send_cb = QtWidgets.QCheckBox(Form)
        self.timer_send_cb.setObjectName("timer_send_cb")
        self.gridLayout.addWidget(self.timer_send_cb, 3, 1, 1, 1)
        self.hex_send = QtWidgets.QCheckBox(Form)
        self.hex_send.setObjectName("hex_send")
        self.gridLayout.addWidget(self.hex_send, 3, 0, 1, 1)
        self.dw = QtWidgets.QLabel(Form)
        self.dw.setObjectName("dw")
        self.gridLayout.addWidget(self.dw, 3, 3, 1, 1)
        self.hex_receive = QtWidgets.QCheckBox(Form)
        self.hex_receive.setObjectName("hex_receive")
        self.gridLayout.addWidget(self.hex_receive, 3, 4, 1, 1)
        self.formGroupBox = QtWidgets.QGroupBox(Form)
        self.formGroupBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.formGroupBox.sizePolicy().hasHeightForWidth())
        self.formGroupBox.setSizePolicy(sizePolicy)
        self.formGroupBox.setMinimumSize(QtCore.QSize(230, 0))
        self.formGroupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.formGroupBox.setAutoFillBackground(False)
        self.formGroupBox.setObjectName("formGroupBox")
        self.formLayout = QtWidgets.QFormLayout(self.formGroupBox)
        self.formLayout.setContentsMargins(10, 10, 10, 10)
        self.formLayout.setSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.s1__lb_1 = QtWidgets.QLabel(self.formGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s1__lb_1.sizePolicy().hasHeightForWidth())
        self.s1__lb_1.setSizePolicy(sizePolicy)
        self.s1__lb_1.setObjectName("s1__lb_1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.s1__lb_1)
        self.s1__box_1 = QtWidgets.QPushButton(self.formGroupBox)
        self.s1__box_1.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s1__box_1.sizePolicy().hasHeightForWidth())
        self.s1__box_1.setSizePolicy(sizePolicy)
        self.s1__box_1.setAutoRepeatInterval(100)
        self.s1__box_1.setDefault(True)
        self.s1__box_1.setObjectName("s1__box_1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.s1__box_1)
        self.s1__lb_2 = QtWidgets.QLabel(self.formGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s1__lb_2.sizePolicy().hasHeightForWidth())
        self.s1__lb_2.setSizePolicy(sizePolicy)
        self.s1__lb_2.setObjectName("s1__lb_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.s1__lb_2)
        self.s1__box_2 = QtWidgets.QComboBox(self.formGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s1__box_2.sizePolicy().hasHeightForWidth())
        self.s1__box_2.setSizePolicy(sizePolicy)
        self.s1__box_2.setObjectName("s1__box_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.s1__box_2)
        self.s1__lb_3 = QtWidgets.QLabel(self.formGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s1__lb_3.sizePolicy().hasHeightForWidth())
        self.s1__lb_3.setSizePolicy(sizePolicy)
        self.s1__lb_3.setObjectName("s1__lb_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.s1__lb_3)
        self.s1__box_3 = QtWidgets.QComboBox(self.formGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s1__box_3.sizePolicy().hasHeightForWidth())
        self.s1__box_3.setSizePolicy(sizePolicy)
        self.s1__box_3.setObjectName("s1__box_3")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.s1__box_3)
        self.s1__lb_4 = QtWidgets.QLabel(self.formGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s1__lb_4.sizePolicy().hasHeightForWidth())
        self.s1__lb_4.setSizePolicy(sizePolicy)
        self.s1__lb_4.setObjectName("s1__lb_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.s1__lb_4)
        self.s1__box_4 = QtWidgets.QComboBox(self.formGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s1__box_4.sizePolicy().hasHeightForWidth())
        self.s1__box_4.setSizePolicy(sizePolicy)
        self.s1__box_4.setObjectName("s1__box_4")
        self.s1__box_4.addItem("")
        self.s1__box_4.addItem("")
        self.s1__box_4.addItem("")
        self.s1__box_4.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.s1__box_4)
        self.s1__lb_5 = QtWidgets.QLabel(self.formGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s1__lb_5.sizePolicy().hasHeightForWidth())
        self.s1__lb_5.setSizePolicy(sizePolicy)
        self.s1__lb_5.setObjectName("s1__lb_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.s1__lb_5)
        self.s1__box_5 = QtWidgets.QComboBox(self.formGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s1__box_5.sizePolicy().hasHeightForWidth())
        self.s1__box_5.setSizePolicy(sizePolicy)
        self.s1__box_5.setObjectName("s1__box_5")
        self.s1__box_5.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.s1__box_5)
        self.s1__lb_6 = QtWidgets.QLabel(self.formGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s1__lb_6.sizePolicy().hasHeightForWidth())
        self.s1__lb_6.setSizePolicy(sizePolicy)
        self.s1__lb_6.setObjectName("s1__lb_6")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.s1__lb_6)
        self.s1__box_6 = QtWidgets.QComboBox(self.formGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s1__box_6.sizePolicy().hasHeightForWidth())
        self.s1__box_6.setSizePolicy(sizePolicy)
        self.s1__box_6.setObjectName("s1__box_6")
        self.s1__box_6.addItem("")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.s1__box_6)
        self.close_button = QtWidgets.QPushButton(self.formGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_button.sizePolicy().hasHeightForWidth())
        self.close_button.setSizePolicy(sizePolicy)
        self.close_button.setObjectName("close_button")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.close_button)
        self.open_button = QtWidgets.QPushButton(self.formGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_button.sizePolicy().hasHeightForWidth())
        self.open_button.setSizePolicy(sizePolicy)
        self.open_button.setObjectName("open_button")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.open_button)
        self.state_label = QtWidgets.QLabel(self.formGroupBox)
        self.state_label.setText("")
        self.state_label.setTextFormat(QtCore.Qt.AutoText)
        self.state_label.setScaledContents(True)
        self.state_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.state_label.setObjectName("state_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.state_label)
        self.gridLayout.addWidget(self.formGroupBox, 0, 10, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.s4__send_3 = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s4__send_3.sizePolicy().hasHeightForWidth())
        self.s4__send_3.setSizePolicy(sizePolicy)
        self.s4__send_3.setObjectName("s4__send_3")
        self.gridLayout_3.addWidget(self.s4__send_3, 0, 0, 1, 1)
        self.s4__send_5 = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s4__send_5.sizePolicy().hasHeightForWidth())
        self.s4__send_5.setSizePolicy(sizePolicy)
        self.s4__send_5.setObjectName("s4__send_5")
        self.gridLayout_3.addWidget(self.s4__send_5, 0, 2, 1, 1)
        self.s4__send_7 = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s4__send_7.sizePolicy().hasHeightForWidth())
        self.s4__send_7.setSizePolicy(sizePolicy)
        self.s4__send_7.setObjectName("s4__send_7")
        self.gridLayout_3.addWidget(self.s4__send_7, 1, 0, 1, 1)
        self.s4__send_8 = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s4__send_8.sizePolicy().hasHeightForWidth())
        self.s4__send_8.setSizePolicy(sizePolicy)
        self.s4__send_8.setObjectName("s4__send_8")
        self.gridLayout_3.addWidget(self.s4__send_8, 1, 1, 1, 1)
        self.s4__send_6 = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s4__send_6.sizePolicy().hasHeightForWidth())
        self.s4__send_6.setSizePolicy(sizePolicy)
        self.s4__send_6.setObjectName("s4__send_6")
        self.gridLayout_3.addWidget(self.s4__send_6, 1, 2, 1, 1)
        self.s4__send_11 = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s4__send_11.sizePolicy().hasHeightForWidth())
        self.s4__send_11.setSizePolicy(sizePolicy)
        self.s4__send_11.setObjectName("s4__send_11")
        self.gridLayout_3.addWidget(self.s4__send_11, 2, 0, 1, 1)
        self.s4__send_10 = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s4__send_10.sizePolicy().hasHeightForWidth())
        self.s4__send_10.setSizePolicy(sizePolicy)
        self.s4__send_10.setObjectName("s4__send_10")
        self.gridLayout_3.addWidget(self.s4__send_10, 2, 1, 1, 1)
        self.s4__send_4 = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s4__send_4.sizePolicy().hasHeightForWidth())
        self.s4__send_4.setSizePolicy(sizePolicy)
        self.s4__send_4.setObjectName("s4__send_4")
        self.gridLayout_3.addWidget(self.s4__send_4, 2, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 1, 10, 1, 1)
        self.verticalGroupBox = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalGroupBox.sizePolicy().hasHeightForWidth())
        self.verticalGroupBox.setSizePolicy(sizePolicy)
        self.verticalGroupBox.setObjectName("verticalGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalGroupBox)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.s2__receive_text = QtWidgets.QTextBrowser(self.verticalGroupBox)
        self.s2__receive_text.setReadOnly(True)
        self.s2__receive_text.setObjectName("s2__receive_text")
        self.verticalLayout.addWidget(self.s2__receive_text)
        self.gridLayout.addWidget(self.verticalGroupBox, 0, 0, 3, 10)
        self.groupBox = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.s4__send_2 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s4__send_2.sizePolicy().hasHeightForWidth())
        self.s4__send_2.setSizePolicy(sizePolicy)
        self.s4__send_2.setObjectName("s4__send_2")
        self.gridLayout_2.addWidget(self.s4__send_2, 0, 0, 1, 3)
        self.s1__box_7 = QtWidgets.QComboBox(self.groupBox)
        self.s1__box_7.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s1__box_7.sizePolicy().hasHeightForWidth())
        self.s1__box_7.setSizePolicy(sizePolicy)
        self.s1__box_7.setIconSize(QtCore.QSize(16, 16))
        self.s1__box_7.setObjectName("s1__box_7")
        self.s1__box_7.addItem("")
        self.s1__box_7.addItem("")
        self.s1__box_7.addItem("")
        self.s1__box_7.addItem("")
        self.s1__box_7.addItem("")
        self.s1__box_7.addItem("")
        self.gridLayout_2.addWidget(self.s1__box_7, 1, 0, 1, 1)
        self.s4__send_1 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s4__send_1.sizePolicy().hasHeightForWidth())
        self.s4__send_1.setSizePolicy(sizePolicy)
        self.s4__send_1.setObjectName("s4__send_1")
        self.gridLayout_2.addWidget(self.s4__send_1, 1, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 1, 2, 1, 1)
        self.s1__box_9 = QtWidgets.QComboBox(self.groupBox)
        self.s1__box_9.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s1__box_9.sizePolicy().hasHeightForWidth())
        self.s1__box_9.setSizePolicy(sizePolicy)
        self.s1__box_9.setIconSize(QtCore.QSize(16, 16))
        self.s1__box_9.setObjectName("s1__box_9")
        self.s1__box_9.addItem("")
        self.s1__box_9.addItem("")
        self.s1__box_9.addItem("")
        self.s1__box_9.addItem("")
        self.s1__box_9.addItem("")
        self.s1__box_9.addItem("")
        self.s1__box_9.addItem("")
        self.s1__box_9.addItem("")
        self.s1__box_9.addItem("")
        self.s1__box_9.addItem("")
        self.s1__box_9.addItem("")
        self.s1__box_9.addItem("")
        self.s1__box_9.addItem("")
        self.s1__box_9.addItem("")
        self.s1__box_9.addItem("")
        self.s1__box_9.addItem("")
        self.gridLayout_2.addWidget(self.s1__box_9, 2, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_2.addWidget(self.pushButton_9, 2, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 2, 2, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 3, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_2.addWidget(self.pushButton_8, 3, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 3, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 2, 10, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_4.addWidget(self.pushButton_10, 3, 0, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_17.sizePolicy().hasHeightForWidth())
        self.pushButton_17.setSizePolicy(sizePolicy)
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_4.addWidget(self.pushButton_17, 1, 2, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_4.addWidget(self.pushButton_7, 1, 1, 1, 1)
        self.LE_8 = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LE_8.sizePolicy().hasHeightForWidth())
        self.LE_8.setSizePolicy(sizePolicy)
        self.LE_8.setObjectName("LE_8")
        self.gridLayout_4.addWidget(self.LE_8, 1, 0, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_16.sizePolicy().hasHeightForWidth())
        self.pushButton_16.setSizePolicy(sizePolicy)
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout_4.addWidget(self.pushButton_16, 0, 2, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_4.addWidget(self.pushButton_6, 0, 1, 1, 1)
        self.LE_7 = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LE_7.sizePolicy().hasHeightForWidth())
        self.LE_7.setSizePolicy(sizePolicy)
        self.LE_7.setObjectName("LE_7")
        self.gridLayout_4.addWidget(self.LE_7, 0, 0, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_20.sizePolicy().hasHeightForWidth())
        self.pushButton_20.setSizePolicy(sizePolicy)
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout_4.addWidget(self.pushButton_20, 3, 2, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_4.addWidget(self.pushButton_11, 3, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_4.addWidget(self.pushButton_5, 4, 2, 1, 1)
        self.s1__box_10 = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s1__box_10.sizePolicy().hasHeightForWidth())
        self.s1__box_10.setSizePolicy(sizePolicy)
        self.s1__box_10.setObjectName("s1__box_10")
        self.s1__box_10.addItem("")
        self.s1__box_10.addItem("")
        self.s1__box_10.addItem("")
        self.s1__box_10.addItem("")
        self.s1__box_10.addItem("")
        self.s1__box_10.addItem("")
        self.gridLayout_4.addWidget(self.s1__box_10, 4, 1, 1, 1)
        self.s1__box_8 = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s1__box_8.sizePolicy().hasHeightForWidth())
        self.s1__box_8.setSizePolicy(sizePolicy)
        self.s1__box_8.setObjectName("s1__box_8")
        self.s1__box_8.addItem("")
        self.s1__box_8.addItem("")
        self.s1__box_8.addItem("")
        self.s1__box_8.addItem("")
        self.s1__box_8.addItem("")
        self.s1__box_8.addItem("")
        self.s1__box_8.addItem("")
        self.gridLayout_4.addWidget(self.s1__box_8, 4, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 3, 10, 3, 1)
        self.verticalGroupBox_2 = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalGroupBox_2.sizePolicy().hasHeightForWidth())
        self.verticalGroupBox_2.setSizePolicy(sizePolicy)
        self.verticalGroupBox_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.verticalGroupBox_2.setTitle("")
        self.verticalGroupBox_2.setObjectName("verticalGroupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalGroupBox_2)
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.s3__send_text = QtWidgets.QTextEdit(self.verticalGroupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s3__send_text.sizePolicy().hasHeightForWidth())
        self.s3__send_text.setSizePolicy(sizePolicy)
        self.s3__send_text.setObjectName("s3__send_text")
        self.verticalLayout_2.addWidget(self.s3__send_text)
        self.gridLayout.addWidget(self.verticalGroupBox_2, 4, 0, 1, 10)
        self.s2__clear_button = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s2__clear_button.sizePolicy().hasHeightForWidth())
        self.s2__clear_button.setSizePolicy(sizePolicy)
        self.s2__clear_button.setObjectName("s2__clear_button")
        self.gridLayout.addWidget(self.s2__clear_button, 3, 9, 1, 1)
        self.s2__save_button_2 = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s2__save_button_2.sizePolicy().hasHeightForWidth())
        self.s2__save_button_2.setSizePolicy(sizePolicy)
        self.s2__save_button_2.setObjectName("s2__save_button_2")
        self.gridLayout.addWidget(self.s2__save_button_2, 3, 5, 1, 1)
        self.s3__send_button = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s3__send_button.sizePolicy().hasHeightForWidth())
        self.s3__send_button.setSizePolicy(sizePolicy)
        self.s3__send_button.setObjectName("s3__send_button")
        self.gridLayout.addWidget(self.s3__send_button, 5, 9, 1, 1)
        self.s3__clear_button = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s3__clear_button.sizePolicy().hasHeightForWidth())
        self.s3__clear_button.setSizePolicy(sizePolicy)
        self.s3__clear_button.setObjectName("s3__clear_button")
        self.gridLayout.addWidget(self.s3__clear_button, 5, 5, 1, 1)
        self.formGroupBox1 = QtWidgets.QGroupBox(Form)
        self.formGroupBox1.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.formGroupBox1.sizePolicy().hasHeightForWidth())
        self.formGroupBox1.setSizePolicy(sizePolicy)
        self.formGroupBox1.setTitle("")
        self.formGroupBox1.setObjectName("formGroupBox1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.formGroupBox1)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.formGroupBox1)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.formGroupBox1)
        self.lineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setFrame(False)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.label_2 = QtWidgets.QLabel(self.formGroupBox1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.formGroupBox1)
        self.lineEdit_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setFrame(False)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.gridLayout.addWidget(self.formGroupBox1, 5, 0, 1, 4)
        self.verticalGroupBox.raise_()
        self.verticalGroupBox_2.raise_()
        self.formGroupBox.raise_()
        self.s3__send_button.raise_()
        self.formGroupBox.raise_()
        self.hex_send.raise_()
        self.timer_send_cb.raise_()
        self.lineEdit_3.raise_()
        self.dw.raise_()
        self.groupBox.raise_()
        self.groupBox_2.raise_()
        self.groupBox_3.raise_()
        self.hex_receive.raise_()
        self.s2__save_button_2.raise_()
        self.s2__clear_button.raise_()
        self.s3__clear_button.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit_3.setText(_translate("Form", "1000"))
        self.timer_send_cb.setText(_translate("Form", "定时发送"))
        self.hex_send.setText(_translate("Form", "Hex发送"))
        self.dw.setText(_translate("Form", "ms/次"))
        self.hex_receive.setText(_translate("Form", "Hex接收"))
        self.formGroupBox.setTitle(_translate("Form", "串口操作"))
        self.s1__lb_1.setText(_translate("Form", "串口检测            "))
        self.s1__box_1.setText(_translate("Form", "检测串口"))
        self.s1__lb_2.setText(_translate("Form", "串口选择："))
        self.s1__lb_3.setText(_translate("Form", "波特率："))
        self.s1__box_3.setItemText(0, _translate("Form", "115200"))
        self.s1__box_3.setItemText(1, _translate("Form", "2400"))
        self.s1__box_3.setItemText(2, _translate("Form", "4800"))
        self.s1__box_3.setItemText(3, _translate("Form", "9600"))
        self.s1__box_3.setItemText(4, _translate("Form", "14400"))
        self.s1__box_3.setItemText(5, _translate("Form", "19200"))
        self.s1__box_3.setItemText(6, _translate("Form", "38400"))
        self.s1__box_3.setItemText(7, _translate("Form", "57600"))
        self.s1__box_3.setItemText(8, _translate("Form", "76800"))
        self.s1__box_3.setItemText(9, _translate("Form", "12800"))
        self.s1__box_3.setItemText(10, _translate("Form", "230400"))
        self.s1__box_3.setItemText(11, _translate("Form", "460800"))
        self.s1__lb_4.setText(_translate("Form", "数据位："))
        self.s1__box_4.setItemText(0, _translate("Form", "8"))
        self.s1__box_4.setItemText(1, _translate("Form", "7"))
        self.s1__box_4.setItemText(2, _translate("Form", "6"))
        self.s1__box_4.setItemText(3, _translate("Form", "5"))
        self.s1__lb_5.setText(_translate("Form", "校验位："))
        self.s1__box_5.setItemText(0, _translate("Form", "N"))
        self.s1__lb_6.setText(_translate("Form", "停止位："))
        self.s1__box_6.setItemText(0, _translate("Form", "1"))
        self.close_button.setText(_translate("Form", "关闭串口"))
        self.open_button.setText(_translate("Form", "打开串口"))
        self.groupBox_3.setTitle(_translate("Form", "信息查询/设置"))
        self.s4__send_3.setText(_translate("Form", "恢复出厂"))
        self.s4__send_5.setText(_translate("Form", "复位系统"))
        self.s4__send_7.setText(_translate("Form", "版本信息"))
        self.s4__send_8.setText(_translate("Form", "系统信息"))
        self.s4__send_6.setText(_translate("Form", "BMS信息"))
        self.s4__send_11.setText(_translate("Form", "传感器信息"))
        self.s4__send_10.setText(_translate("Form", "手掌信息"))
        self.s4__send_4.setText(_translate("Form", "底盘信息"))
        self.verticalGroupBox.setTitle(_translate("Form", "接收区"))
        self.groupBox.setTitle(_translate("Form", "舵机板设置"))
        self.s4__send_2.setText(_translate("Form", "开启设置"))
        self.s1__box_7.setItemText(0, _translate("Form", "2"))
        self.s1__box_7.setItemText(1, _translate("Form", "3"))
        self.s1__box_7.setItemText(2, _translate("Form", "4"))
        self.s1__box_7.setItemText(3, _translate("Form", "5"))
        self.s1__box_7.setItemText(4, _translate("Form", "6"))
        self.s1__box_7.setItemText(5, _translate("Form", "7"))
        self.s4__send_1.setText(_translate("Form", "舵机ID设置"))
        self.pushButton.setText(_translate("Form", "全部松轴"))
        self.s1__box_9.setItemText(0, _translate("Form", "3"))
        self.s1__box_9.setItemText(1, _translate("Form", "0"))
        self.s1__box_9.setItemText(2, _translate("Form", "1"))
        self.s1__box_9.setItemText(3, _translate("Form", "2"))
        self.s1__box_9.setItemText(4, _translate("Form", "3"))
        self.s1__box_9.setItemText(5, _translate("Form", "4"))
        self.s1__box_9.setItemText(6, _translate("Form", "5"))
        self.s1__box_9.setItemText(7, _translate("Form", "6"))
        self.s1__box_9.setItemText(8, _translate("Form", "7"))
        self.s1__box_9.setItemText(9, _translate("Form", "8"))
        self.s1__box_9.setItemText(10, _translate("Form", "9"))
        self.s1__box_9.setItemText(11, _translate("Form", "10"))
        self.s1__box_9.setItemText(12, _translate("Form", "20"))
        self.s1__box_9.setItemText(13, _translate("Form", "50"))
        self.s1__box_9.setItemText(14, _translate("Form", "100"))
        self.s1__box_9.setItemText(15, _translate("Form", "1000"))
        self.pushButton_9.setText(_translate("Form", "定时打印"))
        self.pushButton_3.setText(_translate("Form", "全部锁轴"))
        self.pushButton_4.setText(_translate("Form", "循环运动开"))
        self.pushButton_8.setText(_translate("Form", "循环运动关"))
        self.pushButton_2.setText(_translate("Form", "舵机归中"))
        self.groupBox_2.setTitle(_translate("Form", "底盘控制板设置"))
        self.pushButton_10.setText(_translate("Form", "预留"))
        self.pushButton_17.setText(_translate("Form", "底盘锁轴"))
        self.pushButton_7.setText(_translate("Form", "减速度设置"))
        self.LE_8.setText(_translate("Form", "7"))
        self.pushButton_16.setText(_translate("Form", "底盘松轴"))
        self.pushButton_6.setText(_translate("Form", "加速度设置"))
        self.LE_7.setText(_translate("Form", "7"))
        self.pushButton_20.setText(_translate("Form", "打印超声波"))
        self.pushButton_11.setText(_translate("Form", "预留"))
        self.pushButton_5.setText(_translate("Form", "超声ID设置"))
        self.s1__box_10.setItemText(0, _translate("Form", "d0"))
        self.s1__box_10.setItemText(1, _translate("Form", "d2"))
        self.s1__box_10.setItemText(2, _translate("Form", "d4"))
        self.s1__box_10.setItemText(3, _translate("Form", "d6"))
        self.s1__box_10.setItemText(4, _translate("Form", "d8"))
        self.s1__box_10.setItemText(5, _translate("Form", "da"))
        self.s1__box_8.setItemText(0, _translate("Form", "e8"))
        self.s1__box_8.setItemText(1, _translate("Form", "d0"))
        self.s1__box_8.setItemText(2, _translate("Form", "d2"))
        self.s1__box_8.setItemText(3, _translate("Form", "d4"))
        self.s1__box_8.setItemText(4, _translate("Form", "d6"))
        self.s1__box_8.setItemText(5, _translate("Form", "d8"))
        self.s1__box_8.setItemText(6, _translate("Form", "da"))
        self.s3__send_text.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">sys-msg$</p></body></html>"))
        self.s2__clear_button.setText(_translate("Form", "清除"))
        self.s2__save_button_2.setText(_translate("Form", "保存"))
        self.s3__send_button.setText(_translate("Form", "发送"))
        self.s3__clear_button.setText(_translate("Form", "清除"))
        self.label.setText(_translate("Form", "已接收："))
        self.label_2.setText(_translate("Form", "已发送："))

